### ISSUE TITLE
候補が表示されない。

### ISSUE THREAD

**Issue by myuhe** [hchbaw/auto-fu.zsh#1]
初めまして、myuheといいます。
auto-fu.zsh素晴らしいですね。愛用させてもらってます。
ところで当方の環境では、0.0.1.3以降のバージョンで正常に動作しませんでした。
現象としては、postdisplayは表示されるのですが、候補が表示されません。
なお、.zshrcにauto-fu.zshの設定だけしたものでも試してみましたが、改善ありませんでした。
また、コンパイルの有無も関係ないようでした。
0.0.1.2より古いものは問題なく動作しているようです。

当方の環境は
zsh 4.3.10 (i686-pc-linux-gnu)
ubuntu 10.04
です。

以下のように設定しています。
source ~/.zsh/auto-fu.zsh
zstyle ':auto-fu:highlight' input bold
zstyle ':auto-fu:highlight' completion fg=red,bold
zstyle ':auto-fu:highlight' completion/one fg=white,bold,underline
zstyle ':auto-fu:var' postdisplay $'\n-azfu-'
zstyle ':auto-fu:var' disable magic-space

zle-line-init () {auto-fu-init;}; zle -N zle-line-init

**Comment by hchbaw** [comment]
setopt extended_glob

をあらかじめしておいてみてもらうとよいみたいです！
http://twitter.com/myuhe/status/26992163857

ありがとうございます！

**Comment by myuhe** [comment]
無事、動作しました。
ありがとうございました！！

**Comment by hchbaw** [comment]
extended_glob が off な場合でも動くようにしてみましたー。
レポート本当にありがとうございます！！
