### ISSUE TITLE
Clean exit with Ctrl-d and different behavior for Ctrl-d

### ISSUE THREAD

**Issue by vaeth** [hchbaw/auto-fu.zsh#10]
When exiting zsh with Ctrl-d (if auto-fu is used) the exit status is nonzero which is irritating for remote or chroot shells. The reson is that the function

afu-eof-maybe () {
  local eof="$1"; shift
  [[ "$BUFFER" != '' ]] || { $eof; return }
  "$@"
}

is called with $1=exit, and the status during $eof is nonzero, because the previous test has nonzero status. A simple inversion of the logic would fix this, i.e. the second line of the above function would just have to be replaced by

   [[ -z $BUFFER ]] && { $eof; return }

As a somewhat related issue, I would think that a slightly different behavior of Ctrl-d for nonempty lines would be more intuitive: I would like that Ctrl-d clears not only a character but the whole rest of the line, and if there is no such rest then the whole line is cleared (so that pressing Ctrl-d at most three times indeed exits the shell). In other words, I would like to see instead of "$@" in the above function some code (or function) like:

if (($#BUFFER > CURSOR))
then zle kill-line
else zle kill-whole-line
fi

It would be really great if such a behavior could be enabled at least optionally.

**Comment by hchbaw** [comment]
> [[ -z $BUFFER ]] && { $eof; return }

Thank you very much for the detailed reports. Argh... I'll commit it shortly!

> As a somewhat related issue, I would think that a slightly different behavior of Ctrl-d

Oh I'm very sorry for the inconveniences.
I see that the Ctrl-d stuff will be needed some tweaks like you seggested for somepoint, but it is _NOT_ documented how to do it. (and it is not supported well when using 'auto-fu-zcompile'.)
I'll look into it.

Thank you very much for the suggestions and detailed reports!

**Comment by hchbaw** [comment]
Thank you very much for the your efforts, vaeth!
