### ISSUE TITLE
Install help, please?

### ISSUE THREAD

**Issue by joe9** [hchbaw/auto-fu.zsh#13]
This is how I sourced auto-fu.zsh into my zshrc:

http://codepad.org/gJdSz0cs

$ cat 06-auto-fu.zsh 
# !/usr/bin/zsh
# First, we set sane options for the standard completion system:

autoload -Uz compinit is-at-least
compinit -D -u
zstyle ':completion:_' completer _complete
zstyle ':completion:_' list-colors \${(s.:.)LS_COLORS}
zstyle ':completion:_' menu select=1 # interactive
zstyle ':completion:_' accept-exact-dirs true
zstyle ':completion:_' path-completion false
if is-at-least 4.3.10
then  zstyle ':completion:_' format \"%B%F{yellow}%K{blue}%d%k%f%b\"
else  zstyle ':completion:*' format \"%B%d%b\"
fi
# Now we source ${PN}

source /usr/share/zsh/site-contrib/auto-fu.zsh/auto-fu.zsh
# Finally, we configure ${PN}

zstyle ':auto-fu:highlight' input
zstyle ':auto-fu:highlight' completion bold,fg=blue
zstyle ':auto-fu:highlight' completion/one fg=blue
zstyle ':auto-fu:var' postdisplay # \$'\n-azfu-'
# zstyle ':auto-fu:var' enable all
# zstyle ':auto-fu:var' track-keymap-skip opp
# zstyle ':auto-fu:var' disable magic-space

zle-line-init() auto-fu-init
zle -N zle-line-init
zle -N zle-keymap-select auto-fu-zle-keymap-select
# Starting a line with a space or tab or quoting the first word
# or escaping a word should deactivate auto-fu for that line/word.
# This is useful e.g. if auto-fu is too slow for you in some cases.

zstyle ':auto-fu:var' autoable-function/skiplines '[[:blank:]\\\"'\'']_'
zstyle ':auto-fu:var' autoable-function/skipwords '[\\]_'
# Let Ctrl-d successively remove tail of line, whole line, and exit

kill-line-maybe() {
   if ((\$#BUFFER > CURSOR))
   then  zle kill-line
   else  zle kill-whole-line
   fi
}
zle -N kill-line-maybe
bindkey '\C-d' kill-line-maybe
# Keep Ctrl-d behavior also when auto-fu is active

afu+orf-ignoreeof-deletechar-list() {
   afu-eof-maybe afu-ignore-eof zle kill-line-maybe
}
afu+orf-exit-deletechar-list() {
   afu-eof-maybe exit zle kill-line-maybe
}
# vim: set et sw=2:

When I do source the above file, I get:

source 06-auto-fu.zsh  
source 06-auto-fu.zsh  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded  
with-afu~: job table full or recursion limit exceeded 

Any thoughts on what I am missing, please?

Thanks
Joe

**Comment by vaeth** [comment]
I recognize these lines as part of my gentoo ebuild.
I remember that I had a similar issue once and spent hours to figure out the cause. Finally, the problem was with colliding versions of zsh-fu-zsh and zsh-syntax-highlighting: Upgrading both to the latest git release made the issue magically disappear.

**Comment by hchbaw** [comment]
Hi, Joe!

I've managed to get it working without any errors with
http://codepad.org/gJdSz0cs.

(just source 06-auto-fu.zsh in my ~/.zshrc)

I suspect that some other configration are conflicting with.

Please show your complete .zshrc if you don't care to open it public.
If you do care, please show below command output for the reference.

---

zmodload zsh/parameter

## for k v in ${(kv)options}; do print $k $v; done

**Comment by joe9** [comment]
Hello Takeshi Banse,

Thanks for your quick response.

> I've managed to get it working without any errors with
> http://codepad.org/gJdSz0cs.

I copied the above code to the file : http://codepad.org/0LrI1b82

This is the shell history of what I did: http://codepad.org/rAIFNE4I

and, these are the errors:

source
06-auto-fu.zsh.does_not_work

source
06-auto-fu.zsh.does_not_work

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

with-afu~: job table full or recursion limit
exceeded

> I suspect that some other configration are conflicting with.
> 
> Please show your complete .zshrc if you don't care to open it public.
> If you do care, please show below command output for the reference.
> 
> ---
> 
> zmodload zsh/parameter
> 
> ## for k v in ${(kv)options}; do print $k $v; done

This is the output of the above command: http://codepad.org/e7WKv3GU

Please let me know if you need more details. My zshrc is split into
multiple files, hence, it is kind of painful to paste it out.

Thanks again
Joe

**Comment by joe9** [comment]
Hello Vaeth,

> I remember that I had a similar issue once and spent hours to figure out
> the cause. Finally, the problem was with colliding versions of zsh-fu-zsh
> and zsh-syntax-highlighting: Upgrading both to the latest git release made
> the issue magically disappear.
> 
> I am on the latest version for both, I believe. the 9999 ebuilds, if that
> is what you are referring to. Installed them both today.

Thanks
Joe

**Comment by joe9** [comment]
Hello Takeshi Banse,

> Thanks for your quick response.
> 
> > I've managed to get it working without any errors with
> > http://codepad.org/gJdSz0cs.
> 
> I copied the above code to the file : http://codepad.org/0LrI1b82
> 
> This is the shell history of what I did: http://codepad.org/rAIFNE4I
> 
> and, these are the errors:
> 
> source
> 06-auto-fu.zsh.does_not_work
> 
> source
> 06-auto-fu.zsh.does_not_work
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> with-afu~: job table full or recursion limit
> exceeded
> 
> > I suspect that some other configration are conflicting with.
> > 
> > Please show your complete .zshrc if you don't care to open it public.
> > If you do care, please show below command output for the reference.
> > 
> > ---
> > 
> > zmodload zsh/parameter
> > 
> > ## for k v in ${(kv)options}; do print $k $v; done
> 
> This is the output of the above command: http://codepad.org/e7WKv3GU

fyi, This is the completion related portion of my zshrc:
http://codepad.org/e7WKv3GU

Thanks
Joe

**Comment by joe9** [comment]
Hello Takeshi Banse,

> fyi, This is the completion related portion of my zshrc:
> http://codepad.org/e7WKv3GU

Above is a wrong paste, this is the correct one: http://codepad.org/tQ9zkX6F

Thanks and Sorry for the bother,
Joe

**Comment by hchbaw** [comment]
Hi, Joe!

Thank you for your reports for finding the problem.
- joe9 notifications@github.com [2013-02-24 15:12]:
  > >
  > > ----
  > > zmodload zsh/parameter
  > > for k v in ${(kv)options}; do print $k $v; done
  > > ----
  > >
  > 
  > This is the output of the above command: http://codepad.org/e7WKv3GU

This helps and I can reproduce the error now!

Please turn off rcexpandparam while sourcing the auto-fu.zsh.
This can be accomplished like below;

---

# Now we source ${PN}

() {
  # temporally turn off rcexpandparam while `source`ing the auto-fu.zsh
  setopt localoptions no_rcexpandparam
  source /usr/share/zsh/site-contrib/auto-fu.zsh/auto-fu.zsh

## }

The error does not signal any more here for me.
I hope this helps you, too!

**Comment by joe9** [comment]
Hello Takeshi Banse,

> Please turn off rcexpandparam while sourcing the auto-fu.zsh.
> This can be accomplished like below;
> 
> ---
> 
> # Now we source ${PN}
> 
> () {
> 
> # temporally turn off rcexpandparam while `source`ing the auto-fu.zsh
> 
> setopt localoptions no_rcexpandparam
> source /usr/share/zsh/site-contrib/auto-fu.zsh/auto-fu.zsh
> 
> ## }
> 
> The error does not signal any more here for me.
> I hope this helps you, too!

It works now. Thanks.

Joe
