### ISSUE TITLE
used along with zsh-syntax-highlighting.

### ISSUE THREAD

**Issue by joe9** [hchbaw/auto-fu.zsh#14]
Hello,

I noticed this line in your Readme: TODO: play nice with zsh-syntax-highlighting.

I use zsh-syntax-highlighting.

I notice (being a newbie) that it does not matter whether I source auto-fu.zsh before or after sourcing zsh-syntax-highlighting.

Just wanted to check about the recommended approach (source it before zsh-syntax-highlighting or after)?

Thanks
Joe

**Comment by hchbaw** [comment]
Hi, Joe! Thanks very much for your feedback!

For now, the order does not matter if you use with zsh-syntax-highlighting only.
But if you use it with some other zsh-contribs, it will be matter.

I've been playing/experimenting with `select-word-style` + `url-quote-magic` + `zsh-syntax-highlighting`.
In this particular case, I have to source/configure these things in this order.
1. autoload and configure `select-word-style` and `url-quote-magic` then
2. source `zsh-syntax-highlighting` and at last
3. source `auto-fu.zsh`

So, I want to say that please source `auto-fu.zsh` at the very last of `~/.zshrc` :)

(Ah sorry.
If you want to play with these combination with the recent zsh-syntax-highlighting, you also need this patch
Sorry for the inconvenience, I will push this out for some time.)

``` patch
diff --git a/auto-fu.zsh b/auto-fu.zsh
index 009891d..163603b 100644
--- a/auto-fu.zsh
+++ b/auto-fu.zsh
@@ -1401,7 +1401,7 @@ afu-initialize-register-zle-contrib-all () {
           # _zsh_highlight only
           afu-initialize-register-zle-contrib~ $bname $uname t
           ;;
-        ((#b)(*) '&& _zsh_highlight')
+        ((#b)(*) '-- "$@" && _zsh_highlight')
           # _zsh_highlight plus custom widget
           afu-initialize-register-zle-contrib~ $bname \
             ${${widgets[${match}]}#user:} nil $uname

```

**Comment by joe9** [comment]
Can you please check this commit into the pu branch?

**Comment by hchbaw** [comment]
I've pushed this hunk into `pu`.

Thank you for your suggestion!
