### ISSUE TITLE
Disable menu completion

### ISSUE THREAD

**Issue by PythonNut** [hchbaw/auto-fu.zsh#26]
Thank you for this excellent script. I have _thb_ running on my ZSH alongside zsh-syntax-highlight

I have menu completion configured to be extra-verbose. It's on the slow side and I would rather it not be triggered on self-insert. Is there a way to disable the menu completion aspect such that the highlighting in the line is the only thing I see?

Thanks,
PythonNut

**Comment by hchbaw** [comment]
Thank you very much for your interest!

I'm not quite sure; probably I missed the point. But I suspect that below code will help your needs some point...

```
# highjack afu-comppost function
afu-comppost () {
  # If this is unset, the list of matches will never be listed
  # according to zshall(1)
  compstate[list]=

  typeset -g afu_one_match_p=
  (( $compstate[nmatches] == 1 )) && afu_one_match_p=t

  afu_curcompleter=$_completer
}
```

**Comment by PythonNut** [comment]
Thank you! That works perfectly.
