### ISSUE TITLE
breakage with upcoming zsh-5.0.3

### ISSUE THREAD

**Issue by vaeth** [hchbaw/auto-fu.zsh#30]
When using auto-fu.zsh with the current git version of zsh (which perhaps will be released soon as zsh-5.0.3), the prompt and command line are printed twice for every command.

I was not able to track whether this is due to a bug of zsh-5.0.3 or due to some changed behaviour of zsh-5.0.3.

**Comment by vaeth** [comment]
I forgot to mention that I tested only with the pu branch.

Experiments show that the problem disappears if the command "zle -I" is removed from the afu-line-init() function.
This removal also caused no obvious problems with zsh-5.0.2, but I have no idea whether this is a proper fix.

**Comment by hchbaw** [comment]
Hi, @vaeth!

Thank you very much for reporting!
I will take a look shortly.

**Comment by hchbaw** [comment]
I've pushed the changes.
`pu`, `next` and `thb` need this change if you are using the versions of > zsh-5.0.2.

Thank you very much @vaeth for your efforts!

**Comment by vaeth** [comment]
Thanks a lot! Works like a charm on zsh-5.0.3-test1 and also on earlier versions like zsh-5.0.2 or zsh-4.3.17
