### ISSUE TITLE
implement bookmarks

### ISSUE THREAD

**Issue by 257** [hchbaw/auto-fu.zsh#35]
could you please implement the notion of bookmarks for paths which are most frequently used? much more explained here:
https://github.com/fish-shell/fish-shell/issues/1467

**Comment by hchbaw** [comment]
Sorry, I'm not sure what to do with https://github.com/fish-shell/fish-shell/issues/1419 (make 'bind \b suppress-autosuggestion' play nice with the actual deletion ) about bookmarks.

There are some projects that seems do such jobs on https://github.com/unixorn/awesome-zsh-plugins.

**Comment by 257** [comment]
sorry, bad link. updated to:
https://github.com/fish-shell/fish-shell/issues/1467
