### ISSUE TITLE
[Feature Request] Does not send unaccepted completion after enter pressed

### ISSUE THREAD

**Issue by HerringtonDarkholme** [hchbaw/auto-fu.zsh#39]
Thanks for hchbaw san's splendid plugin. It works well enough for me.

However, sometimes I don't want to accept the completion and just press enter, but auto-fu does send unaccepted completion to execution. Since the completion is still in gray color, intuitively it should not be sent, at least for an end-user like me.

For example, I want to replace a file with a new one while keeping the old one under another name. Like:

``` bash
mv new-file .
mv old-file old-file-back
mv new-file old-file*-back # * stands for cursor position, I have typed what I want
# and auto-fu adds what I don't want
# send this line clobbers old-file-back :(
```

Also, if I want to `cd` to a directory, auto-fu will automatically add undesirable subdirectory to the path I type(less harmful than the above case indeed).

Auto suggestion of other shells, notable fish's, does behave like what I want(not sending unaccepted completion). Probably because it is more intuitive.

I'm a terminal zsh-user, but I guess this can be implemented in [zle-line-finish](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Special-Widgets), can't it?

I found it can be done in afu+accept-line function by assigning LBUFFER to BUFFER, but I cannot ensure it is free of hassle.

**Comment by hchbaw** [comment]
Yes, this behavior is not good default.

It would be better to be done in `afu+accept-line` or `my-accept-line` which calls `afu+accept-line` rather than `zle-line-finish` because the formers theoretically could access some internal variables.

I don't tested much but below snippet could do the job for the reference.

``` sh
my-accept-line () {
  [[ -z "${afu_one_match_p-}" ]] && ((afu_in_p==1)) && {
    BUFFER="$buffer_cur"
  }
  zle afu+accept-line
}
zle -N my-accept-line

bindkey -M afu "^M" my-accept-line   
```

**Comment by HerringtonDarkholme** [comment]
Thanks! It works perfectly!
