### ISSUE TITLE
Doesn't auto-fu.zsh support `visual` ?

### ISSUE THREAD

**Issue by aiya000** [hchbaw/auto-fu.zsh#46]
Hi, thank you for before day 😄 :

I hope to this behavior

1. $KEYMAP enters `afu-vicmd`
2. Input `v` or `V`
3. Select somewhere
4. Input x
    - ==> Delete selected area

But auto-fu.zsh delete only one char

For example.

```
# prompt
$ aaaaaaabaaaaaa
         ^______

# and input x

$ aaaaaaaaaaaaa
```

(`^` means the cursor point)  
(`_` means the selected block)

- - -

Does auto-fu.zsh support `visual` ? :smiley:

**Comment by hchbaw** [comment]
Yes and no :sweat:

As far as I can tell it doesn't touch `vicmd` stuff much, so (I hope, too) it should support zsh's builtin stuff like the visual-mode etc automatically.
But on the other hand `afu-vicmd` might break many things.

Personally, I have been using `vicmd` keymap along side of `bindkey -e` for a long time now.
My simplified `.zshrc` looks like below: (it works for me.)

```sh
bindkey -e

autoload -Uz compinit
compinit -C

bindkey '^[^[' vi-cmd-mode # XXX: This is not prefixed "afu+"

echok () {
  echo "\n***${KEYMAP}***"
  zle reset-prompt
}
zle -N echok
bindkey '^X^X' echok
bindkey -M vicmd '^X' echok

source ~/c/auto-fu.zsh/auto-fu.zsh # XXX: Sorry hard coding
zle-line-init () {auto-fu-init;}; zle -N zle-line-init
zle -N zle-keymap-select auto-fu-zle-keymap-select
```

The keymap `afu-vicmd` is for customizing `vicmd` keybindings when using with `afu` keymap.
In the past I thought it could be useful… But it is not yet necessary for me :sweat_smile: 

You might try to use `vicmd` keymap directly.

**Comment by aiya000** [comment]
It works for me too!
Very thanks :smile: 👍
