### ISSUE TITLE
errors on startup when auto-fu.zsh is sourced

### ISSUE THREAD

**Issue by joe6** [hchbaw/auto-fu.zsh#6]
Cannot rebind self-insert: user:url-quote-magic
Cannot rebind backward-delete-char: user:backward-delete-char
Cannot rebind backward-kill-word: user:backward-kill-word
Cannot rebind kill-line: user:kill-line
Cannot rebind kill-whole-line: user:kill-whole-line
Cannot rebind kill-word: user:kill-word
Cannot rebind magic-space: user:magic-space
Cannot rebind yank: user:yank
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
(eval):1: bad pattern: ^[[?1002h^[[?1049h^[[?1h^[=^[[1
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
(eval):1: bad pattern: ^[[?1002h^[[?1049h^[[?1h^[=^[[1
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
(eval):1: bad pattern: ^[[?1002h^[[?1049h^[[?1h^[=^[[1
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
(eval):1: bad pattern: ^[[?1002h^[[?1049h^[[?1h^[=^[[1
--(~)-----------------------------------------------------------------------------------(pts/7@main)--

**Comment by lepht** [comment]
I still receive this error. Any comment on how to resolve it?

**Comment by sheerun** [comment]
The same

**Comment by hchbaw** [comment]
Oh sorry, I use `cat` as the basic building block.

At the meantime, please alias `cat` as your favorite after sourcing.

**Comment by wangxiaomo** [comment]
[https://github.com/hchbaw/auto-fu.zsh/issues/23](https://github.com/hchbaw/auto-fu.zsh/issues/23)
fixed.
