### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by joe6** [hchbaw/auto-fu.zsh#7]
afu-register-zle-accept-line:3: command not found: v
afu-register-zle-accept-line:3: command not found: v
afu-register-zle-accept-line:3: command not found: v
afu-register-zle-toggle:5: command not found: v

Hello,

I see the above errors when I start zsh with the auto-fu.zsh sourced. Wondering if you have any thoughts on how to fix them.

Thanks
Joe

**Comment by hchbaw** [comment]
Hi, thank you very much for reporting the bug!

I'm very sorry. I cannot reproduce these errors.
I guess that these errors are triggered some zsh options, and I don't make auto-fu.zsh compatible with.
So, please show me your zsh options with below command,

```
zmodload zsh/parameter; for k in ${(ok)options};do echo $k ${options[$k]};done
```

By the way, I suspect `setopt no_shwordsplit` will fix these errors hopefully.

**Comment by joe6** [comment]
Hello,

I am very sorry for opening the issue. It was my configuration that was messed up. I had cat aliased to vimpager and there was no vimpager on my system. I also had a bunch of alias -s suffixes. I am not sure which one of these was interfering with auto-fu.zsh.

Once, I removed the alias on cat, auto-fu.zsh did not have any startup errors.

btw, I could not get auto-fu.zsh to show the dropdown list of items. I am not sure what I am missing. I sourced auto-fu.zsh into my .zshrc file. I meant to dig through why it was not working, and, whether something in my configuration was messing-up things for auto-fu.zsh. But, if you can think of anything, please let me know.

btw, this is the list of my options: http://codepad.org/Wj2oYvuY

Thanks a lot for your help.
Siva

**Comment by hchbaw** [comment]
Hi,

>  cat aliased to vimpager 

Oh my bad, I use cat as the basic building block here and there.
For the time being, please source auto-fu.zsh before setting up the aliases.
Once auto-fu.zsh sourced, it does not use any *nix commads at runtime, hopefully :)
I'm very sorry for the inconvenience.

> btw, I could not get auto-fu.zsh to show the dropdown list of items.

I guess for example,

``` zsh
autoload -Uz compinit && compinit # `compinit -C` if you sure
zstyle ':completion:*' menu select=0
```

and hit tab key when completion list is shown, please.

The `menu` style can have lots of values on the `zsh-compsys(1)` manual page's `Standard Styles` section.
For now, I have no idea if this does not help.

Hope this helps.

**Comment by joe6** [comment]
Hello,

> For the time being, please source auto-fu.zsh before setting up the aliases.
> Thanks, will do. That is not a problem at all.

I seem to be missing something from configuration.

I did the below on the zsh command line

--(~/etc/zsh/auto-fu-zsh)---------------------------------------------------------------(pts/4@main)--
source auto-fu.zsh
--(~/etc/zsh/auto-fu-zsh)---------------------------------------------------------------(pts/4@main)--
autoload -Uz compinit && compinit  
--(~/etc/zsh/auto-fu-zsh)---------------------------------------------------------------(pts/4@main)--
zstyle ':completion:*' menu select=0
--(~/etc/zsh/auto-fu-zsh)---------------------------------------------------------------(pts/4@main)--
ls a

but, the dropdown did not pop-up.
Do I have to do anything more? Sorry for the bother.

Thanks

**Comment by hchbaw** [comment]
Hi,
Oh, I forgot something;( I'm very sorry.

How about below these series of command?

``` zsh
autoload -Uz compinit && compinit # `compinit -C` if you sure
zstyle ':completion:*' menu select=0

source auto-fu.zsh
zle-line-init () {auto-fu-init;}; zle -N zle-line-init
zstyle ':completion:*' completer _oldlist _complete
zle -N zle-keymap-select auto-fu-zle-keymap-select # ← This is optional
```

The `zle-line-init () {auto-fu-init;}; zle -N zle-line-init` actually turns auto-stuff on, hopefully.

Regards.
