### ISSUE TITLE
afu-track-keymap:15: permission denied:

### ISSUE THREAD

**Issue by dakrone** [hchbaw/auto-fu.zsh#8]
When I use auto-fu.zsh on a machine over SSH, I get:

```
afu-track-keymap:15: permission denied:
```

Every time I hit enter at the zsh prompt. This is using auto-fu.zsh from git (on the `pu` branch) with zsh 5.0.0.

**Comment by hchbaw** [comment]
Oh I'm very sory for the inconvenience.

I will take a look into it shortly.

**Comment by hchbaw** [comment]
Do you get the same error if you do not use it over SSH?
(I suspect that the zsh version on your remote side machine's)

By the way, I assume that you are using emacs these days rather than vim and you are not using 'opp.zsh', so for the meantime please remove this line from your .zshrc:

```
zle -N zle-keymap-select auto-fu-zle-keymap-select
```

**Comment by hchbaw** [comment]
I hope 6790632 fixes this, can you confirm?

**Comment by dakrone** [comment]
Yep, that fixes it, thanks! :)
